title: Nicole D. Muszynski
logo: /Nicole-Muszynski/nm.jpg
description: PhD Student in Biomedical Engineering at Vanderbilt University
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky

# Site Author
author:
  name             : "Nicole D Muszynski"
  avatar           : "nm.jpeg"
  bio              : "Biomedical Engineering Ph.D. Student at Vanderbilt University"
  location         : "Nashville, Tennessee"
  employer         :
  googlescholar    : "https://scholar.google.com/citations?user=8toIV4sAAAAJ&hl=en"
  email            : "nicole.d.muszynski@vanderbilt.edu"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "muszynn"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "nicole-muszynski-45082965"
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "VIIBRE_lab"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
  researchgate     : "https://www.researchgate.net/profile/Nicole-Muszynski-2"
