title: Nicole D. Muszynski
logo: /Nicole-Muszynski/nm.jpg
description: <PhD Student in Biomedical Engineering at Vanderbilt University
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
