title: Nicole D. Muszynski
logo: /Nicole-Muszynski/nm.jpg
description: Biomedical Engineer *Vanderbilt University* 

[***Projects with Interactive CADs***](/Nicole-Muszynski/Interactive-CADs)

  
[***Gastrointestinal SQUID Lab***](/Nicole-Muszynski/SQUID-Lab)

  
[***Vanderbilt Institute for Intergrative Biosystems and Education Research***](/Nicole-Muszynski/Wikswo-VIIBRE)

  
[***Curriculum Vitae***](/Nicole-Muszynski/CV)

  
[***Skills and Interests***](/Nicole-Muszynski/SI)

show_downloads: false
google_analytics:
theme: jekyll-theme-dinky



