title: Nicole D. Muszynski
logo: /Nicole-Muszynski/nm.jpg
description: PhD Student in Biomedical Engineering at Vanderbilt University

description: **Email** nicole.d.muszynski@vanderbilt.edu

description: [<img height="38" width="38" src="https://unpkg.com/simple-icons@v5/icons/googlescholar.svg" />](https://scholar.google.com/citations?user=8toIV4sAAAAJ&hl=en) 
description: [<img height="38" width="38" src="https://unpkg.com/simple-icons@v5/icons/researchgate.svg" />](https://www.researchgate.net/profile/Nicole-Muszynski-2) 
description: [<img height="38" width="38" src="https://unpkg.com/simple-icons@v5/icons/linkedin.svg" />](https://www.linkedin.com/in/nicole-muszynski-45082965/) 
description: [<img height="38" width="38" src="https://unpkg.com/simple-icons@v5/icons/instagram.svg" />](https://www.instagram.com/perpetually_coco/) 
description: [<img height="38" width="38" src="https://unpkg.com/simple-icons@v5/icons/github.svg" />](https://github.com/muszynn) 


show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
